config/routes.rb
Rails.application.routes.draw do
  root 'muttees#index'
  resources :muttees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/muttee.rb
class Muttee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/muttees_controller.rb
class MutteesController < ApplicationController
  before_action :set_muttee, only: [:show, :edit, :update, :destroy]

  # GET /muttees
  # GET /muttees.json
  def index
    @muttees = Muttee.all
  end

  # GET /muttees/1
  # GET /muttees/1.json
  def show
  end

  # GET /muttees/new
  def new
    @muttee = Muttee.new
  end

  # GET /muttees/1/edit
  def edit
  end

  # POST /muttees
  # POST /muttees.json
  def create
    @muttee = Muttee.new(muttee_params)

    respond_to do |format|
      if @muttee.save
        format.html { redirect_to @muttee, notice: 'Muttee was successfully created.' }
        format.json { render :show, status: :created, location: @muttee }
      else
        format.html { render :new }
        format.json { render json: @muttee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /muttees/1
  # PATCH/PUT /muttees/1.json
  def update
    respond_to do |format|
      if @muttee.update(muttee_params)
        format.html { redirect_to @muttee, notice: 'Muttee was successfully updated.' }
        format.json { render :show, status: :ok, location: @muttee }
      else
        format.html { render :edit }
        format.json { render json: @muttee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /muttees/1
  # DELETE /muttees/1.json
  def destroy
    @muttee.destroy
    respond_to do |format|
      format.html { redirect_to muttees_url, notice: 'Muttee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_muttee
      @muttee = Muttee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def muttee_params
      params.require(:muttee).permit(:title, :mutter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/muttees_helper.rb
module MutteesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMutter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/muttees/_form.html.erb
<%= form_with(model: muttee, local: true) do |form| %>
  <% if muttee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(muttee.errors.count, "error") %> prohibited this muttee from being saved:</h2>

      <ul>
      <% muttee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :muttee_title %>
  </div>

  <div class="field">
    <%= form.label :mutter %>
    <%= form.text_field :mutter, id: :muttee_mutter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/muttees/edit.html.erb
<h1>Editing Muttee</h1>

<%= render 'form', muttee: @muttee %>

<%= link_to 'Show', @muttee %> |
<%= link_to 'Back', muttees_path %>

app/views/muttees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Muttees</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Mutter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @muttees.each do |muttee| %>
      <tr>
        <td><%= muttee.title %></td>
        <td><%= muttee.mutter %></td>
        <td><%= link_to 'Show', muttee %></td>
        <td><%= link_to 'Edit', edit_muttee_path(muttee) %></td>
        <td><%= link_to 'Destroy', muttee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Muttee', new_muttee_path %>

app/views/muttees/new.html.erb
<h1>New Muttee</h1>

<%= render 'form', muttee: @muttee %>

<%= link_to 'Back', muttees_path %>

app/views/muttees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @muttee.title %>
</p>

<p>
  <strong>Mutter:</strong>
  <%= @muttee.mutter %>
</p>

<%= link_to 'Edit', edit_muttee_path(@muttee) %> |
<%= link_to 'Back', muttees_path %>